name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        c_compiler: [gcc, clang, cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl

    steps:
    - uses: actions/checkout@v4

    - name: Set build output directory
      id: strings
      shell: bash
      run: echo "build_output_dir=${{ github.workspace }}/build" >> $GITHUB_OUTPUT

    - name: Configure CMake
      run: >
        cmake -B "${{ steps.strings.outputs.build_output_dir }}"
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S "${{ github.workspace }}"

    - name: Build
      run: >
        cmake --build "${{ steps.strings.outputs.build_output_dir }}"
        --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{ steps.strings.outputs.build_output_dir }}
      run: ctest --build-config ${{ matrix.build_type }}

    - name: Run Executable
      shell: bash
      run: |
        os="${{ runner.os }}"
        build_dir="${{ steps.strings.outputs.build_output_dir }}"
        executable="sso"

        if [ "$os" = "Windows" ]; then
          executable="sso.exe"
          executable_path="$build_dir/${{ matrix.build_type }}/$executable"
        else
          executable_path="$build_dir/$executable"
        fi

        echo "Checking if executable exists: $executable_path"
        if [ -f "$executable_path" ]; then
          echo "Executable found, running it (expected to crash for debug demo)"
          "$executable_path" || echo "Program crashed as expected (exit code ignored)"
        else
          echo "Executable not found: $executable_path"
          exit 1
        fi
